<h1>Events</h1>

<h2>Sponsored events. Whenever we can.</h2>
<time datetime='2012-01-30T06:00:00-07:00'>Jan 30</time>
<h4>First Spring Meeting <em>(6PM - 7PM @ Gould Simpson 701)</em></h4>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut dapibus, purus a commodo tincidunt, diam mi mattis lectus, id euismod dolor elit eu lorem. Sed eu posuere ligula. Aenean et augue quam. Cras diam ante, volutpat at dictum sed, volutpat eu diam. Pellentesque euismod adipiscing dictum. Suspendisse bibendum interdum ligula, sed ultrices tellus placerat nec. Nunc semper, orci sed dictum egestas, nisi tortor tempus sapien, a elementum sapien mauris vestibulum ipsum. Ut quam augue, ultricies ac viverra a, faucibus sagittis sem. Praesent at volutpat augue. Morbi fermentum, eros ut rutrum laoreet, ipsum turpis tempus diam, sit amet congue purus mauris vel dui. Phasellus auctor libero semper quam fringilla tempor. Aenean sodales est at diam rutrum vitae bibendum nisi porta. Cras et risus est. Aenean a elit orci, vitae venenatis eros. Ut et risus ligula, id euismod arcu. Suspendisse potenti.</p>

<time datetime='2012-02-06T06:00:00-07:00'>Feb 6</time>
<h4>First Spring Meeting <em>(6PM - 7PM @ Gould Simpson 701)</em></h4>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut dapibus, purus a commodo tincidunt, diam mi mattis lectus, id euismod dolor elit eu lorem. Sed eu posuere ligula. Aenean et augue quam. Cras diam ante, volutpat at dictum sed, volutpat eu diam. Pellentesque euismod adipiscing dictum. Suspendisse bibendum interdum ligula, sed ultrices tellus placerat nec. Nunc semper, orci sed dictum egestas, nisi tortor tempus sapien, a elementum sapien mauris vestibulum ipsum. Ut quam augue, ultricies ac viverra a, faucibus sagittis sem. Praesent at volutpat augue. Morbi fermentum, eros ut rutrum laoreet, ipsum turpis tempus diam, sit amet congue purus mauris vel dui. Phasellus auctor libero semper quam fringilla tempor. Aenean sodales est at diam rutrum vitae bibendum nisi porta. Cras et risus est. Aenean a elit orci, vitae venenatis eros. Ut et risus ligula, id euismod arcu. Suspendisse potenti.</p>
